### ISSUE TITLE
Add Support for custom prefix

### ISSUE THREAD

**Issue by gklesczewski** [BoltR/Hangfire.Redis.StackExchange#6]
When running multiple instances of HangFire within an application environment, each instance should have its own prefix. 

The existing code for the standard prefix works well, if we expose the prefix property the hosting application can change the value as needed.

**Comment by BoltR** [comment]
Is there any reason you cannot use multiple databases to accomplish the same thing?

The fact that the prefix is a static value is actually used in many places in the project, so it's not quite as trivial as making it a public field.

Edit: I suppose this is functionality I should add either way, since you can only use database 0 in clustered mode.

**Comment by gklesczewski** [comment]
I can continue looking into this change if you'd like. At this point, though, I should be able to use the separate queues within Hangfire for separation, for now.

**Comment by BoltR** [comment]
I added support for changing the prefix with commit 48438d2.
However, it will be a little while before I will push the changes to NuGet. So if you end up using it before then please ping back to let me know!

**Comment by BoltR** [comment]
I've released a new version to NuGet which includes support for this. Thus, I am closing the issue.
