### ISSUE TITLE
Nuget package is not up to date

### ISSUE THREAD

**Issue by zlangner** [BoltR/Hangfire.Redis.StackExchange#9]
It appears the nuget package (https://www.nuget.org/packages/Hangfire.Redis.SE/) was last updated on 5-21-2015. So it doesn't include the dashboard changes that were made on 8-17-2015. Can you please update the nuget package assuming that these dashboard changes are stable for production use.

**Comment by BoltR** [comment]
Sorry about that, I'll try to get it updated in the next day or two. 
I've been swamped for the last few months madly updating projects to .NET Core.

**Comment by BoltR** [comment]
I'm afraid that I am going to take longer than initially projected to get the package updated. 

I actually had a package ready which I already had placed on an internal nuget server, and was testing in production. However, it also had a commit in staging that bumped the version number, and package dependency versions.
Instead of just committing that, and uploading I decided I should probably bump the packages again. Updating Hangfire to the latest version deprecates a number of functions that are being used, and breaks the unit tests to the point where they won't compile.
As such, rather than release a version that should work, I am going to spend some time updating things.

Sorry for the delay. It shouldn't get lost in the shuffle this time.

**Comment by BoltR** [comment]
A updated version has now been pushed to both github and nuget. They should now be synced.
